### ISSUE TITLE
Use Replicache with React Native

### ISSUE THREAD

**Issue by altick** [rocicorp/replicache#1005]
Hi, I couldn't find any information about support for replicache on React Native. Is React Native supported platform? In case it's not are there any plans to support RN in the future?

**Comment by aboodman** [comment]
Yes, it should work. You have to hook experimentalKVStore interface up to SQLite as React Native doesn't support IndexedDB.

We don't have a sample of hooking it up to SQLite, but here's a sample of hooking up to WebSQL, which is very similar: https://github.com/rocicorp/replicache-sample-websql

If you pursue this path it would be very helpful to share a skeleton for others.

Thanks!

**Comment by aboodman** [comment]
Subsumed by official support bug: #1013
