### ISSUE TITLE
Interactive tutorial for doc homepage

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#1030]
We've gotten a lot of negative feedback on current doc homepage experience along the lines of:

- I don't want to use next.js
- This feels too magical, can't understand what's going on here

I think we need to start way simpler and walk people through building a Replicache app with as few deps as possible. We've decided to do this in the form of an interactive tutorial/repl.

**Comment by arv** [comment]
Marked "Future" because it does not block the next npm major release but it does seem higher priority than "future" implies

**Comment by aboodman** [comment]
This has long since been completed:

https://doc.replicecache.dev/
