### ISSUE TITLE
Document spaces

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#1035]
Originally how Replicache apps were organized above the protocol was more open.

Now that we have settled into spaces being a more fundamental part of Replicache they should be documented that way. There needs to be a page for spaces, perhaps under "Understand Replicache".

Some of the things to communicate are:

- Spaces are not currently "part of" the Replicache protocol (the stuff represented in push/pull). They are "outside" Replicache in that sense.
- But in practice ~every application of Replicache uses this concept.
- Key constraints on spaces
- I also think it's worth reviewing rest of doc and making sure that spaces are discussed at appropriate times.
- Example data modeling: maybe one easy case (todos) and one hard case (discord)

**Comment by izakfilmalter** [comment]
Spaces confuse me. Would be great to go over some example spaces for common apps, uber / airbnb / gmail.

**Comment by aboodman** [comment]
This has been implemented: https://doc.replicache.dev/strategies/per-space-version
