### ISSUE TITLE
Question: Subscribing to all changes?

### ISSUE THREAD

**Issue by excursus** [rocicorp/replicache#1042]
Is there a way to subscribe to all changes made to replicache, rather than subscribing to individual keys? I'd like to be informed when anything changes in replicache, and get only that change. I see there's a `scan` transaction, which I think would re-run on every change, but I don't see an easy way to obtain only the diff. Is this possible? Thank you.

**Comment by aboodman** [comment]
Yep: https://doc.replicache.dev/api/classes/Replicache#experimentalwatch

**Comment by excursus** [comment]
Awesome, thank!
