### ISSUE TITLE
License Key Socket Connection Timeout

### ISSUE THREAD

**Issue by jordiup** [rocicorp/replicache#1048]
Having trouble getting a license key for getting started 

```bash

npx replicache get-license        

Need to install the following packages:
  replicache@12.2.2
Ok to proceed? (y) 
Welcome. Using Replicache requires registering to acquire a license key.

✔ Your name: … jordi
✔ Company/project/org name or URL: … acme.io
✔ Contact email: … jordi@acme.io
✔ Is your project commercial as defined by the Replicache Terms of Service (https://roci.dev/terms.html#software-licenses)? … no
✔ Do you agree to the Replicache Terms of Service (https://roci.dev/terms.html)? … yes
Fetching License Key...
Sorry, there was an error. Please file a bug at https://github.com/rocicorp/replicache/issues/new with the following information:
Error: Failed to create customer: request to https://replicache-license.herokuapp.com/api/1.0/customer failed, reason: Socket connection timeout
```

**Comment by aboodman** [comment]
Thank you for the report. It appears to be working now, perhaps it was a transient issue. Can you please try again?

**Comment by jordiup** [comment]
Cheers @aboodman, back in business 👍

**Comment by roblonj** [comment]
I am experiencing this issue today.

**Comment by aboodman** [comment]
i believe that it was a temporary blip, can you try again?

**Comment by roblonj** [comment]
@aboodman I didn't notification of your reply. So, I filed a [bug #1056](https://github.com/rocicorp/replicache/issues/1056). It is closed now and we can continue here. 
I have tried multiple times since the last 24 hours to generate a new Replicache license key and still facing the same issue. I have attached a screenshot below. 
![Replicache license error](https://github.com/rocicorp/replicache/assets/63639117/57411368-661e-4f4f-ab03-f3ec0b0bc365)

**Comment by aboodman** [comment]
<img width="1464" alt="CleanShot 2024-06-07 at 09 18 45@2x" src="https://github.com/rocicorp/replicache/assets/80388/6136e24d-3468-4568-b5a7-567449228eb1">

Weird, I just did this one right now. 🤔

**Comment by aboodman** [comment]
What happens when you fetch https://replicache-license.herokuapp.com/api/1.0/customer in a browser? You should see:

<img width="1464" alt="CleanShot 2024-06-07 at 09 22 48@2x" src="https://github.com/rocicorp/replicache/assets/80388/50d930b1-7ae3-47e7-8ea2-da7465965ff4">

**Comment by roblonj** [comment]
Yup. I am the getting the same response when I fetch https://replicache-license.herokuapp.com/api/1.0/customer in a browser. Still cannot generate license.
<img width="1492" alt="Screenshot 2024-06-07 at 7 03 08 PM" src="https://github.com/rocicorp/replicache/assets/63639117/4318b835-3e6d-4d08-880a-f9a3fd5588a4">

**Comment by aboodman** [comment]
Hm, can it be some kind of networking issue? Are you on a VPN or some kind
of corporate network that could be blocking access to heroku?

To workaround, why don't you email ***@***.*** with the details you
want to use (name, email, etc) and we'll get you a license key manually.
