### ISSUE TITLE
Incorrect license link in getting started guide

### ISSUE THREAD

**Issue by atikenny** [rocicorp/replicache#1055]
The link to the licensing page in the getting started guide's code example is pointing to a 404 page.

# Screenshot
![Screenshot](https://github.com/rocicorp/replicache/assets/6061509/51f043b6-aea4-4ecb-9b1d-09aa55800852)

**The link is**: https://doc.replicache.dev/licensing
**The correct link is**: https://doc.replicache.dev/concepts/licensing

**Comment by FleetAdmiralJakob** [comment]
Agree, had the same issue

**Comment by arv** [comment]
@cesara Do you have permission to update the code sandbox?

**Comment by cesara** [comment]
fixed thanks

**Comment by arv** [comment]
Fixed
