### ISSUE TITLE
dropAllDatabases does not respect experimentalCreateKVStore

### ISSUE THREAD

**Issue by NavaceSystem** [rocicorp/replicache#1057]
```
"replicache": "14.2.2",
```

We are trying to use replicache in react-native using the experimentalCreateKVStore with https://github.com/Braden1996/react-native-replicache binding. Everything works fine except for the the `dropAllDatabases` and `dropDatabase` calls. It seems to be ignoring the binding and doing its default "web" stuff. I've traced the minified Replicache code to debug this and below are 2 errors that made me reach this conclusion:

- When calling `dropAllDatabases`, it errors out on this line in replicache `return navigator.userAgent.includes("Firefox")`. It obviously has some FF specific logic but this code shouldn't be running at all. When the `experimentalKVStore` is present it should be calling its `destroy` function.
- If I hard code the above to be false, it continues to error out at `indexedDB.deleteDatabase(t)`. Again IDB is a web specific thing, it shouldn't be running this code at all.

**Comment by aboodman** [comment]
I think this is fixed in Replicache 15. We started releasing this and didn't complete it. I can't remember why. Can you take a look?

**Comment by 1kDustin** [comment]
@NavaceSystem This does seem to work in react native on Replicache 15, but Replicache seems to continue to try and sync once the DB is destroyed. Calling replicache.close() before destroying the DB results in breaking destroyAllDatabases, so I think we're kind of stuck until this one gets figured out

**Comment by aboodman** [comment]
@1kDustin do you have a reproduction or test case that shows what you're seeing? Thanks!

**Comment by aboodman** [comment]
Oops, this was fixed.
