### ISSUE TITLE
how to pass addtional header with the Pull URL

### ISSUE THREAD

**Issue by Biki-das** [rocicorp/replicache#1059]
i have this piece of code 
![Screenshot 2024-07-11 at 11 47 55 PM](https://github.com/rocicorp/replicache/assets/72331432/492c9d4a-37dc-4325-972c-85932505b884)

and i want to pass the bearer token with it? how can i do that please help me with the example of code.

**Comment by Biki-das** [comment]
cc @aboodman

**Comment by arv** [comment]
You would have to create your own `Puller` and `Pusher`. See https://doc.replicache.dev/api/interfaces/ReplicacheOptions#puller and https://doc.replicache.dev/api/interfaces/ReplicacheOptions#pusher
