### ISSUE TITLE
Why is getAuth not in the constructor?

### ISSUE THREAD

**Issue by isaachinman** [rocicorp/replicache#1062]
Going through the docs and getting myself familiarised with Replicache. Liking what I see so far!

However, I expected `getAuth` to go in the class constructor:

```ts
new Replicache({
  getAuth: async () => {
    const refreshedToken = await refreshToken()
    
    return refreshedToken
  }
})
```

Instead, it seems you're meant to assign it _after_ initialisation? Is that right?

```ts
const replicache = new Replicache({ ... })

replicache.getAuth = () => ...
```

What is the thinking behind that design decision? As the contents of `getAuth` are entirely user-provided, people could easily cover any use cases that require differing behaviour over time. 

And two related questions – I'd like to prevent 401s where possible, by refreshing auth proactively:

1. Is it possible to instruct Replicache of the auth TTL, and refresh prior to expiry?
2. If not, is it possible to mutate the `replicache.auth` value at runtime?

**Comment by aboodman** [comment]
> What is the thinking behind that design decision? As the contents of getAuth are entirely user-provided, people could easily cover any use cases that require differing behaviour over time.

No particular reason. I suppose it's sort of an older style API.

> Is it possible to instruct Replicache of the auth TTL, and refresh prior to expiry?

The way that `getAuth` works is that if a push or pull return 401, Replicache calls `getAuth` to get a new token without notifying the user. Replicache doesn't know anything about TTL, it's just responsive to the status code.

If you don't want to return 401 for some reason (ooc - why?) then you can implement `pusher` and `puller` and do whatever auth logic you want, bypassing the Replicache concept of `auth` entirely.

**Comment by isaachinman** [comment]
Understood, thanks!
