### ISSUE TITLE
Track size of bundle on benchmarks page

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#125]
We're already tracking the size of the bundle in a gh action, just need to wire it up to the benchmark UI.

**Comment by aboodman** [comment]
@arv can you do this on a low priority background task?

**Comment by arv** [comment]
The  benchmark UI is not very flexible. We should post the numbers to supabase or something like that and use next.js to generate the json file used in the dashboard.

If we did that we would have more freedom to add other metrics.
