### ISSUE TITLE
We need to do something about mutator signature mismatch after reboot

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#285]
Right now, in TypeScript, we use the pattern of having developers register strongly typed mutators:

```
    this.createShape = rep.register('createShape', async (tx: WriteTransaction, args: CreateShapeArgs) => {
      await createShape(this.mutatorStorage(tx), args);
    });
```

This is great when developer themself is calling the mutator, since it helps them  know what the arguments are supposed to be and pass valid ones.

However, Replicache can also call these functions. Important Replicache can do this with some data that might not match the current version of the code, so there is an opportunity for a confusing runtime exception.

I'm actually not sure how this is even compiling right now. It seems like TS would complain because somewhere somebody is downcasting from JSONValue to strong types. But it's working.

**Comment by arv** [comment]
It is an "unsafe cast". TypeScript cannot now this. We cannot guarantee the right shape either without doing runtime type checks.

**Comment by aboodman** [comment]
I know, but we need to do something to help users avoid this class of weird error.

**Comment by arv** [comment]
Maybe the best practice is to not change the type signature? If you need to change the type you should also change the name.

**Comment by aboodman** [comment]
Ah, of course. This is a nice solution.

This just needs to go in the documentation somewhere then.

@phritz just for the heads up.

**Comment by phritz** [comment]
I am including it in the launch checklist.

**Comment by arv** [comment]
Documented in b7f58e79335f2f6cc6c9c30fa2132c86e623ce05
