### ISSUE TITLE
6.0.0 Tasks

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#300]
We are about to release 6.0.0 which uses diff sync and there is no more diff server.

The API is not backwards compatible. We can take the opportunity and remove things that have been deprecated too.

Tasks

 - [x] ~remove `sync()`~
 - [x] update/review all the readmes
 - [x] update/review JSDoc 
 - [x] remove samples

**Comment by aboodman** [comment]
Do we have a public `push()` ?

**Comment by aboodman** [comment]
Looks like yes. We could keep `sync()` as a convenience for `await Promise.all(push(), pull()`. I go back and forth about this.

Not sure when I'd use it, but seems inevitable that it will be useful.

**Comment by arv** [comment]
> Do we have a public push() ?

Yes

**Comment by arv** [comment]
> We could keep sync() as a convenience for await Promise.all(push(), pull()

I think we need to serialize these or we do not know that we are fully synced afterwards.

**Comment by aboodman** [comment]
I suppose so. Still I guess I'm saying it's not a high priority for me to remove it.

**Comment by arv** [comment]
OK. Let's keep it. It is very trivial...

**Comment by arv** [comment]
Should we also keep syncInterval?

**Comment by arv** [comment]
Talked online... Keep syncInterval for now since we have not implemented error recovery.
