### ISSUE TITLE
We should accept mutators in the constructor (and not later, via `register`)

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#329]
In Replidraw, I discovered that as a user of Replicache you really want the mutators to follow the `Replicache` constructor around. Actually you want both the mutators and subscriptions to do so and once you have that you don't need the rest of `Replicache` maybe!?

https://github.com/rocicorp/replidraw/blob/master/frontend/data.ts#L30

We should do something like this in the SDK directly. Every consumer is going to want it.

Imagining, ideally, something like the constructor accepts an object which has for each field a mutator impl. Then Replicache iterates the keys and registers each mutator and returns something that has all the current functionality of `Replicache` but also exposes each mutator.

In TypeScript, the mutators exposed after construction need to be strongly-typed.

I believe that if we had this we would *not* want to expose a public `register` method, because it's a foot gun: we really don't want people registering mutators late because it would be possible for Replicache to go looking for them before they are registered. Users need to provide the mutators statically at construction time.

**Comment by arv** [comment]
I like it!

**Comment by arv** [comment]
My only concern is that I do not like these to become methods of the Replicache instance. It leads to issues with conflicting names and unclarity what is a mutator or not. We would have to put it under some namespace at least.

```ts
const r = new Replicache({
  mutators: {
    a(tx, args) {
       ...
    },
  },
});
...
await r.mutators.a({x: 1});
```

**Comment by aboodman** [comment]
If we do that I'm really gonna want the subscriptions right next door on `.subscriptions` (ala #344) :)

One other thing here, I could not figure out how to do it but it would be super cool if there was a way to avoid the duplication of the name of the mutator:

```
    createShape: rep.register(
      "createShape",
 ```
 
 I was hopeful that since TypeScript has the concept of literal types that there'd be some way to say something like:
 
 ```
const rep = new Replicache({
  ...
  mut: {
    createShape: async (tx, args: { id: string, shape: Shape }) {
      ....
    }
  }
});
```

... and the result was that `rep.mut.createShape` exists and is a mutator named `createShape` with the type `Promise<void> (args: {id: string, shape: Shape})`.

**Comment by aboodman** [comment]
Side note what do you think of the names `mut` and `sub` to be a little shorter. You type these a lot.

**Comment by arv** [comment]
`mut` seems fine.

I'm not sure what `sub` is? Is it a `Set`/`Array` of all subscriptions?

**Comment by aboodman** [comment]
I realized after suggesting this that `sub` doesn't maybe make sense because it is common to want to create subscriptions for a particular component's lifetime. So we probably just want `rep.useSubscribe()` which is exactly the same function we have now just as a method.

I realize you might have feelings about this, but encourage you to try playing with replidraw or something. Bet you see it my way if you put on your user hat. It's nice to type `rep.` and have intellisense tell you everything you can do, rather than having to remember that there's this other bare function for subscriptions.

Plus one less package to import, etc.
