### ISSUE TITLE
ConnectionLoop: logger not wired up

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#331]
We should wire up the logger, otherwise it's difficult to debug what's going on with the connection loop. Give push and pull a unique prefix so we can tell them apart, too.

**Comment by phritz** [comment]
Since this is in js I assume you want the js to log, but logging in repc is also an option (and frequently useful).

**Comment by arv** [comment]
My suggestion is to add a flag to ReplicacheOptions. This would be passed into repc too

**Comment by arv** [comment]
What I always do when I'm debugging the tests is:

```patch
     this._pullConnectionLoop = new ConnectionLoop({
       invokeSend: () => this._pull(),
       watchdogTimer: () => this.pullInterval,
       debounceDelay: () => 0,
       maxConnections: 1,
+      log: (...args) => console.log('PULL', ...args, Date.now()),
     });
     this._pushConnectionLoop = new ConnectionLoop({
       invokeSend: () => this._invokePush(MAX_REAUTH_TRIES),
       debounceDelay: () => this.pushDelay,
       maxConnections: 1,
+      log: (...args) => console.log('PUSH', ...args, Date.now()),
     });
```

**Comment by aboodman** [comment]
sgtm
