### ISSUE TITLE
let's not deadlock the protocol (was: push endpoint error policies)

### ISSUE THREAD

**Issue by phritz** [rocicorp/replicache#336]
- when the batch endpoint hits an error it has to decide whether to treat it as temporary (stop processing mutations) or permanent (skip this mutation and increment last mutation id). 
- current policy is to treat errors as temporary by default. this is good because it doesn't lose user data. this is bad because it stalls push until the problem is fixed.
- in order to minimize push downtime customers have to be really on top of A) responding to temporary errors as they arise and B) converting unhandled permanent errors (which will surface as temporary errors) into permanent errors so they do the right thing going forward

we need a discussion of this in the user manual

also we have considered a customer configurable timeout that causes the client to remove a mutation is causing a temporary error after some time. this presupposes a synchronous endpoint. we are not sold on this idea.

**Comment by aboodman** [comment]
I think that this is covered by rocicorp/mono#100 so closing this.
