### ISSUE TITLE
Make `replicache-react-util` inherit from `replicache`

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#344]
I was thinking that we should rephrase `replicache-react-util` to expose a new `Replicache` or `ReplicacheReact` class that inherits from the core one and adds `useSubscribe`. That way, along with #329, users would have `useSubscribe` and `useMutator` right as methods next to each other on the same class.

**Comment by arv** [comment]
I'm not sure. Tacking more things on a class when a normal function works just as well seems like the wrong encapsulation to me.

**Comment by aboodman** [comment]
I would usually feel that way too, but ask yourself what the best API design would be if we *only* cared about React. It seems clear to me that the subscription methods would be members of Replicache just as the mutators are proposed to be.

**Comment by arv** [comment]
Maybe, needs a strawman.

**Comment by aboodman** [comment]
The other thing (and this is mostly unrelated) is that it is super hard to keep from accidentally including two copies of Replicache (different versions) the way it works right now. We should have React devs only include one library (the React interface) not two. The React interface should itself include the correct version of Replicache.

**Comment by aboodman** [comment]
Closing this in favor of better proposal here: https://github.com/rocicorp/replicache/issues/393#issuecomment-853959622
