### ISSUE TITLE
replicache.dev.wasm no longer works

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#355]
https://github.com/rocicorp/repc/commit/de0e746cea8182b87ffea158d12cf50e07ae478c changed dev to use a debug build which has a different set of exports than a release/profile build. We need to add back the dev version of the js file if we want to have a debug build.

**Comment by aboodman** [comment]
Argh. I don't want it to complexify setup.

**Comment by aboodman** [comment]
Instead of a `wasmModule` directory is it possible to have a `wasmDirectory` flag, and then depending on whether you import the dev js or not, it finds the right wasm module by itself? I feel like this would also allow us to implicitly pre-load the wasm module which would be awesome.

**Comment by aboodman** [comment]
It seems like this implies that the setup guide will be broken by the new release too. Maybe let's change the setup guide to use the release build. We can have a doc about switching to dev build for debugging purposes.

**Comment by aboodman** [comment]
Sorry for breaking this :-/.
