### ISSUE TITLE
Change docs / examples to use nanoid

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#357]
Basically every simple app needs this. But on the other hand complex apps may want to choose the form of their IDs more carefully.

Thinking something along the lines of:

```js
function newID(byteLen) {
  return Array.from(crypto.getRandomValues(new Uint8Array(byteLen)), (v) =>
    v.toString(16).padStart(2, "0")
  ).join("");
}
```

**Comment by arv** [comment]
I'm torn. I think it would be useful but I also hate bundling unrelated things together.

**Comment by phritz** [comment]
Updating this from recent conversations:
- there is no requirement that successively generated ids sort lexicographically ascending and there is no requirement that these ids are easy to recognize when embedded in key strings (eg, to substitute/compress them). however either of these properties would be useful.
- size of ids impacts performance on several levels, eg, how many (key, hash) records internal nodes can hold, so we are incentivized to keep them as small as we can
- by far the simplest thing we could do is as suggested above: generate N (=128) bits of randomness and base64 encode it. This ensures global uniqueness and results in 24 byte encoded ids (or 25 if we prepend a single version byte). There is no state to keep and no coordination amongst tabs with this approach, and it can live in js.
- we could use the clientid in the id, eg clientid-i where i is a per-profile counter. 
   - this requires keeping state
   - all the repetitions of the clientid would compress well
   - this leaks the clientid where a thing was created. with diffsync, clientids are not a secret, so this isn't necessarily a problem. but it still smells a bit and is unexpected.
   - if we did use clientid with a counter it'd be a good idea for the bindings to prefetch one or more ids so they are immediately available when needed

**Comment by Talor-A** [comment]
my go-to is https://www.npmjs.com/package/nanoid , it might be easier to just link to the package or re-export a wrapper with some sane defaults around `nanoid` than reinvent the wheel :)

**Comment by arv** [comment]
nanoid looks good enough to me. It compiles nicely to something small enough:

```ts
import {nanoid} from 'nanoid';
console.log(nanoid());
```

```sh
npx esbuild test.ts --bundle --minify --format=esm
```

```js
var r=(o=21)=>{let e="",n=crypto.getRandomValues(new Uint8Array(o));for(;o--;){let t=n[o]&63;
t<36?e+=t.toString(36):t<62?e+=(t-26).toString(36).toUpperCase():t<63?e+="_":e+="-"}return e};console.log(r());
```

formatted:

```js
var r = (o = 21) => {
  let e = "",
    n = crypto.getRandomValues(new Uint8Array(o));
  for (; o--; ) {
    let t = n[o] & 63;
    t < 36
      ? (e += t.toString(36))
      : t < 62
      ? (e += (t - 26).toString(36).toUpperCase())
      : t < 63
      ? (e += "_")
      : (e += "-");
  }
  return e;
};
console.log(r());
```

**Comment by aboodman** [comment]
OK given the discussion here, sounds like this wasn't a good idea. Update my proposal to changing the docs and examples to use/recommend nanoid and do nothing else.

**Comment by arv** [comment]
Done
