### ISSUE TITLE
Consider moving index definitions to Replicache constructor

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#367]
Is it useful to create indexes after the Replicache instance has been created?

**Comment by aboodman** [comment]
Huh, that's an interesting simplification. I like it. Let me ponder it for awhile in the background?

Does it simplify implementation?

**Comment by arv** [comment]
I don't think it simplifies things... I just thought it conceptually cleaner since changing index definitions at runtime seems undesirable (but I'm not sure it is, you tell me)

**Comment by aboodman** [comment]
Oops. Duplicated here #602
