### ISSUE TITLE
could not download wasm module

### ISSUE THREAD

**Issue by phritz** [rocicorp/replicache#387]
I would put this down to something transient but the weird thing is it *looks* to my untrained eye like replicache trying to *Pull* (not just fetch) a wasm module?

https://rocicorp.slack.com/archives/C01JJGGS6CU/p1621460870372700

**Comment by arv** [comment]
This error is coming from:

https://github.com/rocicorp/replicache/blob/80a2800a900d2b49a30bf33acc5fd7668e71cc69/src/replicache.ts#L747

**Comment by arv** [comment]
I think what is happening is that pull is waiting for the async operations to download the wasm file, open replicache etc, and then the download fails and it gets reported through all those promise rejections.

**Comment by arv** [comment]
No longer an issue with JS port
