### ISSUE TITLE
Multiple react versions when using yarn

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#393]
When you try to setup a basic Replicache app using yarn you end up getting the multiple React hooks error:

![image (3)](https://user-images.githubusercontent.com/80388/120597927-5b321980-c3e1-11eb-8feb-b26fb3ebfc54.png)

This is because something about yarn dep resolution is different and leads to multiple versions of React installed.

**Comment by aboodman** [comment]
@arv can you take a look at some point. Lots of users have reported this.

**Comment by aboodman** [comment]
A customer suggested removing the `package-lock.json` file from `replicache-react-util` to fix this problem, they say it is a pretty common solution.

I still like the idea of just having `replicache-react-util` change to `replicache-react` and directly pull in `replicache`. Maybe the same way via no lock file? That way it will auto-update to latest compatible major version? WDYT?

**Comment by aboodman** [comment]
Like maybe ideally you just include `replicache-react`, then:

```
dependencies: {
  "replicache-react": "^42.0.0"
}
```

You can import everything from there:

```
import { Replicache, useSubscribe, JSONValue, ...} from "replicache-react"
```

**Comment by arv** [comment]
> You can import everything from there:
> ```js
> import { Replicache, useSubscribe, JSONValue, ...} from "replicache-react"
> ```

I think you have convinced me...

but doesn't this just push the problem somewhere else? `replicache` has no dependencies on React so I do not think that solves the actual problem. For `replicache` we do want a `package-lock.json` so that the tests are hermetic.

`package-lock.json`: It is strange that this is used at all for a dependency? I will have to look more into how this is supposed to work.

**Comment by aboodman** [comment]
Customer suggested removing `package-lock.json` from `replicache-react-util`, not from `replicache`.

**Comment by arv** [comment]
> Customer suggested removing `package-lock.json` from `replicache-react-util`, not from `replicache`.

I get that. I'm just confused why yarn/npm is even looking at that in a dependency.

**Comment by arv** [comment]
Fixed in https://github.com/rocicorp/replicache-react-util/commit/e0f56ade87162443d491c550f167db198ea171e1
