### ISSUE TITLE
Expose push/pull as a JS interface, not an HTTP interface

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#394]
We've had a few customer requests now to implement push/pull as JS functions not HTTP. The reason is because they have some server whose input/output format they do not have complete control over.

In the first instance, the user used FaunaDB, which can accept requests directly from clients without any app server. However, FaunaDB is not a general purpose computing system, the requests have to be in a specific form that represents queries. From https://discord.com/channels/830183651022471199/830183651022471202/845095220789772289:

<img width="765" alt="Screen Shot 2021-06-03 at 7 02 38 AM" src="https://user-images.githubusercontent.com/80388/120683728-b09a1500-c439-11eb-9ddb-3f8d52ae26d3.png">

In the second instance, the user uses Blitz (https://blitzjs.com/). Blitz has a way to generate API endpoints, but they end up conforming to a restricted subset of REST.

Again from Discord https://discord.com/channels/830183651022471199/830183651022471202/850049826808266752:

<img width="991" alt="Screen Shot 2021-06-03 at 7 05 28 AM" src="https://user-images.githubusercontent.com/80388/120684163-15ee0600-c43a-11eb-9e69-cb1c2ae42baa.png">

Generalizing these user requests I can also imagine people wanting to implement Replicache against backends that are already supporting and have tooling setup for e.g., GraphQL, GRPC, whatever. And they are not excited about dropping back down to REST.

**Comment by aboodman** [comment]
@arv @phritz FYI

**Comment by aboodman** [comment]
Summarizing:

<img width="1055" alt="Screen Shot 2021-06-03 at 7 08 01 AM" src="https://user-images.githubusercontent.com/80388/120684494-74b37f80-c43a-11eb-91e0-51ecf407ca49.png">

**Comment by aboodman** [comment]
Is it also possible moving this to a JS interface could remove some weight from the wasm bundle? I don't remember if we're including anything for HTTP in the browser case (I hope not).

**Comment by Talor-A** [comment]
my original proposal was replacing 
```
pushUrl: string
```
with 
```
push: string | (changes: SerializedMutation[]) => Promise<void>
```

though after looking through the source it might make sense to implement push as a fn with type 
```
(changes: SerializedMutation[]) => Promise<boolean>

```
to stay consistent with [`wrapInOnlineCheck`](https://github.com/rocicorp/replicache/blob/2fb88dcf0cbc2c38618aca7ac888c6c803a1acae/src/replicache.ts#L724) and allow retries if the handler implementation fails / is offline?

**Comment by arv** [comment]
> I don't remember if we're including anything for HTTP in the browser case (I hope not).

We are using https://docs.rs/http/0.2.4/http/request/index.html from https://github.com/rocicorp/repc/blob/aae93355b379fe3ddecfef8730f68519cc0023dc/src/sync/push.rs#L114-L123 and https://github.com/rocicorp/repc/blob/aae93355b379fe3ddecfef8730f68519cc0023dc/src/sync/pull.rs#L498-L507. I think @phritz did it this way to unify Rust and Wasm. Making the interface use a higher abstraction would remove this dependency in the Wasm build.

**Comment by aboodman** [comment]
Here is another good argument from the stackblitz discord -- if people use cookies for auth (unrecommended, but common) then they will need to add CSRF tokens to be secure.

<img width="1914" alt="Screen Shot 2021-06-16 at 10 30 29 AM" src="https://user-images.githubusercontent.com/80388/122289288-3f714d80-ce8e-11eb-96aa-c285be22efa8.png">
