### ISSUE TITLE
Expose MIN_DELAY_MS etc

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#395]
The `ConnectionLoop` uses a bunch of configuration values. Some of these are constants in connection-loop.ts and some are passed in through the `ConnectionLoopDelegate`.

We want to expose these in the Replicache API and make them writable (allowing them to change during the lifetime of the Replicache instance).

### Strawman proposal

```ts
interface RequestOptions {
  url?: string;
  auth?: string;
  minDelayMs?: number;
  maxDelayMs?: number;
}

interface PullOptions extends RequestOptions {
  interval?: number;
}

interface PushOptions extends RequestOptions {
  delay?: number;
}
```

And then we extend/change `Replicache`/`ReplicacheOptions`:

```ts
export interface ReplicacheOptions<MD extends MutatorDefs> {
 ...
  pullOptions?: PullOptions;
  pushOptions?: PushOptions;
}
```

On every access to these options we read through to the passed in objects allowing them to change over time. For example:

```ts
const pullOptions = {minDelayMs: 50};
const rep = new Replicache({
  pullOptions,
});

setTimeout(() => {
   pullOptions.minDelayMs = 250;
}, 10_000);
```

this should also work:

```ts
const rep = new Replicache({
  pullOptions: {minDelayMs: 50},
});

setTimeout(() => {
   rep.pullOptions.minDelayMs = 250;
}, 10_000);
```

**Comment by aboodman** [comment]
It feels a little magical to me to have this options object be mutable. That's now how I usually think of options objects. Is it common?

**Comment by arv** [comment]
It is not common.

**Comment by arv** [comment]
We could have a setter...

```js
rep.pullOptions = newPullOptions;
```

but I do not think that is much clearer

**Comment by aboodman** [comment]
Why not expose the options we want to be runtime settable as mutable properties on Replicache? I know it's old school but ... makes sense to me?

**Comment by arv** [comment]
Because there will be like 5 for push and 5 for pull. Seems like it makes things to messy

**Comment by aboodman** [comment]
Alright I guess in that case your proposal make most sense.
