### ISSUE TITLE
replicache.offline does not seem to work

### ISSUE THREAD

**Issue by Talor-A** [rocicorp/replicache#408]
code sample I'm using: 

```tsx
export const App = () => {
  const [replicache, setReplicache] = useState<MyReplicache | null>(null);

  // ... initialize replicache ...

  const [syncing, setSyncing] = useState(false);
  const [online, setOnline] = useState(false);

  useEffect(() => {
    if (replicache) {
      replicache.onSync = (status) => {
        setOnline(replicache.online);
        setSyncing(status);
      };
    }
  }, [replicache]);

  return ...
}
```

when using the above code, `online` always appears to be true, even if I block requests from devtools / go offline. `syncing` does change when requests go out. It also is unclear whether `offline` should be true if an API route 404's / throws an error, perhaps this can be documented

**Comment by arv** [comment]
I do think this broke at some point... and I failed to add test for it so I never noticed it. https://github.com/rocicorp/replicache/blob/main/src/replicache.test.ts

Will work on it.

The online property is supposed to be a heuristics of whether pull/push succeeded
