### ISSUE TITLE
Chat example fails

### ISSUE THREAD

**Issue by knollfear** [rocicorp/replicache#413]
I am following along exactly with the chat app example and I get an error when I try this [sample code](https://js.replicache.dev/guide/render-ui).  The page immediately gives me a big error that says: 

`
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
`

I looked at the repo for replicache-react-util but there isn't a readme or example or test.  package.json is below if that helps. 
I had the latest version of react inst
package.json:
`
{
  "name": "learn-starter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^10.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "replicache": "^6.2.2",
    "replicache-react-util": "^2.2.0"
  }
}
`

**Comment by arv** [comment]
Just fixed this in version 2.3.0 of https://preview.npmjs.com/package/replicache-react-util. If you update you package.json and rerun `yarn`/`npm install` things should work.
