### ISSUE TITLE
Rename replicache-react-util -> replicache-react

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#414]
Can we do this without creating a new package?

**Comment by aboodman** [comment]
@arv

**Comment by aboodman** [comment]
Guess not: https://stackoverflow.com/questions/28371669/renaming-a-published-npm-module.

Well, we should do it sooner rather than later then.

**Comment by arv** [comment]
We can sue `npm deprecate` to tell people to move to the new one though

**Comment by arv** [comment]
Done

**Comment by arv** [comment]
Also updated the docs

**Comment by aboodman** [comment]
🙏
