### ISSUE TITLE
Replay is broken in 6.3.0

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#422]
The arguments passed to rebased mutations are always `undefined`. It appears that something around 0804561967eac69b15195fcdb61c331890798a2d went wrong.

Repo: https://github.com/aboodman/replicache-issue-421/commit/d2fe6dd6744c87eb41b34c99fa6536bffb1d22df (that specific commit).

`npm install`, copy the wasm, start the server, then create a message.

We go into a tight loop fetching replicache-push (because of #421), but otherwise the UI appears to do the right thing with the pending mutation:

<img width="910" alt="Screen Shot 2021-07-01 at 1 42 38 PM" src="https://user-images.githubusercontent.com/80388/124200901-35487500-da72-11eb-8930-7dd84df471be.png">

But then when you refresh the page:

<img width="886" alt="Screen Shot 2021-07-01 at 1 42 58 PM" src="https://user-images.githubusercontent.com/80388/124200924-42fdfa80-da72-11eb-9d9f-1c21d6e33f85.png">

... the pending entry disappears (modulo the colon character).

The reason is because:

<img width="769" alt="Screen Shot 2021-07-01 at 1 44 27 PM" src="https://user-images.githubusercontent.com/80388/124200984-76408980-da72-11eb-98c5-7b1e81174fc8.png">

That entry in the data pulled out of subscribe is all undefined values. The reason for that is because during replay, the args we receive are also undefined:

<img width="1433" alt="Screen Shot 2021-07-01 at 1 45 34 PM" src="https://user-images.githubusercontent.com/80388/124201032-9f611a00-da72-11eb-8e32-682c6aba32bc.png">

**Comment by arv** [comment]
Did you also revert the repc change?

**Comment by arv** [comment]
I'm a bit surprised. The js tests are invoking repc. I guess the rebase test is not working?

**Comment by arv** [comment]
Closing.

I added a comment to the code explaining what the heck was going on. We can continue to use string for the RPC. The type we send over HTTP does not have to match.
