### ISSUE TITLE
Expose experimental KV Store interface

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#444]
Today the key-value store is an implementation detail in Rust. We have two different implementations of this. One is an in memory (hashmap) store and one is backed by IndexedDB.

We are considering exposing the Store interface to JS to allow an application more control. One thing that has been requested is for a way to proxy the store so it can be used in a sandbox.

One issue is that we are not yet convinced we want to commit to exposing this internal implementation detail.

To allow experimenting with this we could expose this as an experimental API, flagged in a clear way.

## Strawman

Add `experimentalStore` to `ReplicacheOptions`. It would be of type `Store` defined in the following way:

```ts
export interface Store {
  read(): Promise<Read>;
  write(): Promise<Write>;
  close(): Promise<void>;
}

export interface Read {
  has(key: string): Promise<boolean>;
  get(key: string): Promise<Uint8Array | undefined>;
}

export interface Write extends Read {
  put(key: string, value: Uint8Array): Promise<void>;
  del(key: string): Promise<void>;
  commit(): Promise<void>;
  rollback(): Promise<void>;
}
```

We might want to consider naming all these types/classes as `ExperimentalFoo`

We already have WIP PRs for this at https://github.com/rocicorp/replicache/pull/427 and https://github.com/rocicorp/repc/pull/366

**Comment by aboodman** [comment]
1. Why expose the memstore and IdbStote implementations?
2. Release isn’t used anywhere. What classes need to be released?

**Comment by aboodman** [comment]
Otherwise LGTM

**Comment by arv** [comment]
1. The reason I was thinking to expose them was so that things that want to proxy Replicache over a membrane then they can instantiate a store on the _dry_ side. Otherwise we depend on them to implement the store locking mechanism correctly which is far from trivial. But maybe as an experiment we can just have them copy/paste our code for now?
2. `Release` is needed but the naming/API could be better. To achieve the right read-write locking mechanism of a store we need a way to release the lock when we are done with `Read` and `Write`. Maybe I should take a stab at refactoring things so that `Store` has a `withRead((r: Read) => Promise<void>): Promise<void>` and `withWrite((r: Write) => Promise<void>): Promise<void>` instead.

**Comment by arv** [comment]
Another option for `Release` might be for us to manage the locking... testing... That worked pretty well. Will update the PR

**Comment by arv** [comment]
`Release` is gone in the PR.
