### ISSUE TITLE
Stop cloning objects returned through ReadTransaction

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#480]
As of https://github.com/rocicorp/replicache/pull/479, we clone the underlying data before returning it via `ReadTransaction::get()` or `::scan()`.

We do this to prevent developer from modifying it any caches inside Replicache.

Instead, we should just return the underlying value but `deepFreeze()` it first, to prevent mutations.

I would like to first get the perf tests to run in-memory tests so we can more easily see the benefit though. See https://github.com/rocicorp/replicache/issues/484.

**Comment by aboodman** [comment]
Apparently the underlying v8 bug is still open so we can't use freeze():

https://bugs.chromium.org/p/chromium/issues/detail?id=980227#c9

I am full of sadness.

In the meantime how about we have the `ReadTransaction.scan()` and `ReadTransaction.get()` methods return `readyonly` types in TypeScript, and neither clone nor freeze their return values. We should also document that these should not be mutated.

The `WriteTransaction.scan()` and `WriteTransaction.get()` methods should continue to return mutable data which is a clone. We can revisit that another time (probably by introducing a new `getMut()` and `scanMut()`.

**Comment by arv** [comment]
I need to verify that we are doing the right thing for the arguments to mutators.

**Comment by arv** [comment]
Here is the clone for replay:

https://github.com/rocicorp/replicache/blob/9e8d7872392c6da5120dc390f7c7970ee9886614/src/sync/pull.ts#L243

We were missing a clone in the initial call to the mutation
