### ISSUE TITLE
Simplify prolly.Map

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#481]
The `prolly.Map` package was fashioned after our experience on Noms, but it never quite grew into what we envisioned, and now we are imagining not using a prolly tree at all.

This should get replaced by a b-tree but in the meantime some small simplifications would make this code easier to read:

1. Get rid of `_pending`. The only reason it exists now is to enable `getPendingKeyChanges()`. We can just maintain a set of changed keys off to the side. It won't be quite as precise as the `_pending` map enables, but...
2. We don't need to use `deepEquals()` to calculate pending key changes. This is forcing us to deep compare every pair of values in the map. Instead we should just track keys that were touched. Occasionally this won't be perfectly precise in case a value changes then changes back, but <meh>. Seems better than crawling this entire object tree each time.

**Comment by arv** [comment]
>     2\. Occasionally this won't be perfectly precise

If we keep the values around then we could compare at the end.
