### ISSUE TITLE
replicache-sample-chat application not working on Safari

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#486]
I get:

```
Unhandled Runtime Error
InvalidStateError: Failed to execute 'objectStore' on 'IDBTransaction': The transaction finished.
```

When I load it at startup. I have tracked this down to this bug in Safari: 

https://github.com/jakearchibald/idb-keyval/commit/1af0a00b1a70a678d2f9cf5e74c55a22e57324c5#r55977709

It appears that you need to immediately use the object store, you cannot delay through a promise resolution.

**Comment by aboodman** [comment]
What's weird is that if I change the `IDBStore.withRead` method like so:

```
  async withRead<R>(fn: (read: Read) => R | Promise<R>): Promise<R> {
    const db = await this._db;
    const tx = db.transaction(OBJECT_STORE, 'readonly');
    return fn(new ReadImpl(tx));
  }
```

... and make the corresponding change to `withWrite` then the sample apps works, even though I leave `read()` and `write()` in place and they are used in other places.

This makes me think that perhaps the Safari bug only happens in relation to when the db is initially constructed.

I tried refactoring such that `IDBStore` has a member which holds `IDBDatabase` directly, rather than `Promise<IDBStore>`. My thought was that I could make then make `read()` synchronous. However, I realized `read` needs to be async for the memory case.

**Comment by arv** [comment]
I applied the patch (man does npm suck with tarballs) and the error goes away.

Safari is still not working correctly though. The data does not show up until the data is pulled.

**Comment by arv** [comment]
Safari replicache-sample-chat is experiencing the issue both with mem store and idb store.

Subscription is not firing.

**Comment by aboodman** [comment]
Hm, I thought I saw it working with the patch.

**Comment by arv** [comment]
Found it!

**Comment by arv** [comment]
Drumroll.... 🥁

**Comment by arv** [comment]
Missing await in sample code!

**Comment by arv** [comment]
https://github.com/rocicorp/replicache-sample-chat/commit/2f6eb56b18d3ae4d47badfde62e1e9c5be8f0fcf

**Comment by arv** [comment]
I'll open a new issue. It should be an error to call put etc after commit!
