### ISSUE TITLE
RFE: Add getMany

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#489]
There are cases where it would be more performant to do multiple reads (and writes) in a batch.

We could add:

```ts
getMany(keys: string[]): Promise<string[]>;
```

To `ReadTransaction`

**Comment by arv** [comment]
And similarly add `putMany` to `WriteTransaction`:

```ts
putMany(entries: [key: string, value: JSONValue]): Promise<void>;
```

**Comment by arv** [comment]
and `delMany`?

**Comment by aboodman** [comment]
Maybe for simplicity we should just change the kv interface to *only* have
{get,put,del,has??} many?

**Comment by arv** [comment]
Fine with me but does not seem like a super high priority at the moment

**Comment by aboodman** [comment]
Is this bug still relevant with https://www.notion.so/Replicaches-All-the-Way-Down-a453ccd8cc97491b9797dc58bc961e9e ?

**Comment by arv** [comment]
It might still make sense. But maybe it is something that we add to the KV store and deal with it under the hood?

**Comment by arv** [comment]
This is all very speculative and lets not keep bugs like that open.
