### ISSUE TITLE
RFE: Expose a timeout for pull and push

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#491]
Right now we default to the browser default fetch timeout (which I think is 30s). We got requests to make this configurable and we used to have a constant for this in the old Rust fetch implementation but it was never exposed and got removed when we started using fetch from JS.

**Comment by aboodman** [comment]
This was requested by SuprDaily.

**Comment by phritz** [comment]
The more things change... https://github.com/rocicorp/repc/issues/360 :)

**Comment by aboodman** [comment]
I'm now wondering if we should do this in light of #575 . If we are going to tell people to implement `push`/`pull` themselves they can just whatever timeout they want.

**Comment by aboodman** [comment]
Gonna go with no for now.
