### ISSUE TITLE
API nit: I wish default values for all options were visible in doc

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#524]
Take something like `minDelayMs` or `maxDelayMs`. You can override these, but it's not easy to know what the default values are. I wish the options were implemented in such a way that they used default values in tyepscript and these value were automatically documented.

**Comment by aboodman** [comment]
@arv is it possible to implement this somehow?

**Comment by arv** [comment]
I agree that this is not very nice.

I do not know how to make this work except for manually documenting this somewhere.
