### ISSUE TITLE
RFE: It sure would be nice if clientID were synchronous

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#542]
I think this means that constructing `Replicache` would have to become *asynchronous* but that would probably be good for other reasons too.

**Comment by arv** [comment]
Should be doable now

**Comment by arv** [comment]
What we really want is an "async" constructor. JS "supports" it but TypeScript does not allow it without going through hoops.

It would be a breaking change and it is pretty uncommon to see:

```ts
const rep = await new Replicache(...);
```

We have been pretty careful to defer things as much as possible. For example it is OK to call `query` before we have inited the DB. It is just that we have to wait for the init inside query./

**Comment by aboodman** [comment]
I was thinking more:

```
Replicache.new()
```

... but maybe another way would be store the client ID in `localStorage` instead? I know `localStorage` is not popular but having `clientID()` be async creates lots of hoops for users to jump through:

https://github.com/rocicorp/replidraw/blob/durable/src/rep.ts

**Comment by aboodman** [comment]
It also seems like making construction async could help with: https://github.com/rocicorp/replicache/issues/456

**Comment by arv** [comment]
Even if we make construction async it is not clear what we actually want to wait for at construction time?

**Comment by aboodman** [comment]
?

`clientID` is currently async: https://doc.replicache.dev/api/classes/Replicache#clientid

It's async, because in order to get the client ID, we need to open the idb db and read from it, which is async:

https://github.com/rocicorp/replicache/blob/main/src/replicache.ts#L319

I'm proposing to instead make construction of Replicache async so that the work to get client ID can be done then, and thereafter `clientID` can be synchronously fetched.

**Comment by aboodman** [comment]
Ping @arv.

**Comment by arv** [comment]
I'm just not convinced that it is better?

Now your react useReplicache etc needs to be async too.

Is async clientID really that painful?

**Comment by aboodman** [comment]
What happens is that right now, you cannot use `clientID` in e.g., getters, because async things are not allowed there. In order to work around this, developers end up creating some wrapper for Replicache like `Data` in Replidraw: https://github.com/rocicorp/replidraw/blob/main/frontend/data.ts#L51 that they construct asynchronously.

So they take a one-time async hit at startup of their app to construct the `Data` wrapper, then from that point on they have everything available synchronously. So no, `useSubscribe` doesn't have to be async with this suggestion.

**Comment by aboodman** [comment]
I found the place where this is super annoying:

You frequently want to call a subscription from `replicache-react` in the constructor to some component, and pass it your own clientID as a parameter. But you can't because `rep.clientID` is a promise and you can't `await` in a constructor.

**Comment by aboodman** [comment]
Another place: marking a function `async` to be able to use `await rep.clientID` changes its return type and sometimes interfaces require/expect the return type to be `void`.

**Comment by aboodman** [comment]
And one more minor one, you can't use `await` inside e.g., `Array.filter`.

**Comment by arv** [comment]
All these have a simple solution which is to read the `clientID` after creation and passing it around. I know you dislike this though.

I'm OK with changing where things are awaited if we want to make another major release we can start sketching on a new API in this issue

**Comment by aboodman** [comment]
For this one, https://github.com/rocicorp/replicache/issues/542#issuecomment-939516112 you either literally have to pass a separate clientID param to the constructor, or else add state to your component so you can wait for the clientID. I don't consider either of those simple.

OTOH, once https://github.com/rocicorp/replicache/issues/541 exists, it would eliminate all the current cases where I need clientID synchronously *and* be more convenient. So we could start there. But I still sort of think that that we should just expose Replicache construction via an async factory and be done with it? It seems like it would simplify things internally too -- we wouldn't have to pass around the db as a promise for example.

**Comment by arv** [comment]
> just expose Replicache construction via an async factory and be done with it

**just** makes it sound super simple. If there was a way to have private constructors in JS (not TS) then it would be easier. What we probably need to do is to either hack it with a sentinel or split implementation from the interface and not expose the implementation class.

```ts
export interface Replicache {
    clientID: string;
    ...
}

export async function newReplicache(...): Replicache {
    const kvStore = new kv.Store();
    const dagStore = new dag.Store(kvStore);
    const clientID = await sync.initClientID(kvStore);
    ...
    return new ReplicacheImpl(kvStore, dagStore, clientID, ...)
}

class ReplicacheImpl implements Replicache {
    ...
}
```

The reason it is bad to just mark the constructor as private in TS is that JS consumers will likely use `new` on it and get something that does not work correctly (especially if they run across and old sample or old documentation that used `new`)

**Comment by aboodman** [comment]
I see. You're right that I wasn't thinking about the plain js users.

**Comment by arv** [comment]
Closing this for now. We expose the client id on the transaction.
