### ISSUE TITLE
Doc: Add "Diff Strategies" section to recipes

### ISSUE THREAD

**Issue by joe-trellick** [rocicorp/replicache#567]
In the [Remote Mutations](https://doc.replicache.dev/guide/remote-mutations) page of the Integration Guide, there's a `TODO` link to "Cookie Monster Manual" in the info box about diff computation. Possibly this would be an adaptation of the contents of [this Roam note](https://roamresearch.com/#/app/aboodman/page/CRCQyTopz).

**Comment by aboodman** [comment]
We actually have a more developed version of this documentation here: https://www.notion.so/Summary-of-Diff-Strategies-28a7577f69f74c6ebf0854a81afb790e - just needs to be docufied

**Comment by aboodman** [comment]
Done: https://doc.replicache.dev/strategies/overview
