### ISSUE TITLE
RFE: Allow server to acknowledge receipt of mutations prior to updating lastMutationID

### ISSUE THREAD

**Issue by whiten** [rocicorp/replicache#604]
I first suggested in https://docs.google.com/document/d/1Cfwwccf1EXX9smyKOExrox2s3pWbnaIrWtyUZCb10xc/edit# a model where a 200 response to a Push request indicated that the server had recorded the mutations it had received, and would eventually apply them, so the client didn't need to continue sending them until `lastMutationID` was updated. It was correctly pointed out there that this optimization makes the server's job harder, because it can no longer respond with 200 unless it has committed these mutations to durable storage, and also that it would be easy for implementations to get this slightly wrong and have mutations get lost.

This ticket suggests that we find some way to do this, so that servers that may sometimes take a while to update `lastMutationID` can inform clients when they have recorded mutations durably, even if their effects haven't been fanned out yet. I envision that we could add an optional response body on push, or allow a header to be included in the response with the id of the last mutation that has been durably recorded (denoting that all earlier ones have been as well). Under both of these schemes, it would be up to servers whether they ever wanted to advertise this, and by default we'd stick with continuing to push mutations that are above `lastMutationId`.

This is not high priority, but seems like a logical protocol enhancement for someday.

**Comment by KeKs0r** [comment]
I am curious what the use case is.

When the push would update the lastMutationId, the client would throw out the optimistic updates for them without having yet pulled the server updates. So the client would temporarily loose that state.
The alternative could be mutations that don't affect client state, but in those cases I am not sure why it would matter. 

Sorry if I am missing something obvious.

**Comment by whiten** [comment]
The Replicache protocol allows the server to apply mutations asynchronously, including over multiple transactions. One can imagine doing a primary mutation, and then enqueuing some work to happen soon after to fan the effects out. Pull can report a `lastMutationID` at or higher than such a mutation only when all of its effects (or at least those that would matter to the initiating client) are visible, to prevent the backtracking you mention.

But, that introduces the possibility that if one of these fanout work queues is taking a long time to complete, the `lastMutationID` reported by pull needs to not be incremented during that delay. Two things need to happen on the client during that time: 1) the mutation that hasn't yet appeared in `lastMutationID` needs to keep being replayed as other changes are pulled from the server, and 2) the client needs to keep sending this mutation on every push until `lastMutationID` moves beyond it. Moreover, the client presumably should keep pushing regularly, as it has changes the server hasn't acknowledged. It makes sense that 1) is required to occur, but 2) seems wasteful of both bandwidth and server load.

I think `lastMutationID` is doing double-duty here, representing both the last mutation that is *fully* visible, and also the last mutation that the server reports to have durably recorded, whether fully fanned out or not. In the example above, as soon as the server has performed the primary mutation and durably enqueued any follow-on work, the client should no longer need to keep sending this mutation with every push. Detaching that acknowledgement from the one that all fan-out work is complete is the goal here.

**Comment by aboodman** [comment]
Putting this on ice until a user requests.

**Comment by arv** [comment]
For the record, I just saw that Datadog uses HTTP 202, Accepted which is similar to this.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202
