### ISSUE TITLE
RFE: Turn the result of `ReadTransaction.scan()` into an interface

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#607]
This would allow developers to implement `WriteTransaction` on the server side which is a real nice pattern for code reuse. See: https://github.com/rocicorp/replidraw/pull/56/commits/385b5d32a53ec067cadd1cb7fed508763ed71cb5#diff-b1688cc87a204ea3f0d8bd85a4c571a7b9fa74f62e731a327b59861f5efe7882R48

**Comment by aboodman** [comment]
This would unblock: https://github.com/rocicorp/replidraw/issues/57 because `deleteAllShapes` needs to first scan to find all shapes, then delete them.

**Comment by aboodman** [comment]
I think probably the better way to do this is to refactor to make `ScanResult` take some kind of dependency as a parameter, that knows how to seek to some particular starting position. Then all the logic related to:

* limit
* prefix vs startAt
* inclusive vs exclusive

Could be shared between implementations of `WriteTransaction::scan()` and it would be much much easier for implementors/users.

Then the implementation of scan might look like:

```
scan(options: ScanOptions) {
  return new ScanResult(new Reader(...));
}
```

Where `Reader` implements an interface that looks like:

```
interface Reader {
  async seek(key: string): Promise<void>
  // return undefined if can't move forward
  async next(): Promise<[key: string, value: ReadonlyJSONValue] | undefined>
}
```

**Comment by arv** [comment]
I had to revert. The PR regressed writeSubRead
