### ISSUE TITLE
Document what can be awaited in Read/WriteTransactions

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#615]
Since we use IndexedDB for persistent storage you cannot await things that goes to the browsers message loop (like fetch, setTimeout, crypto methods). Only things that only use microtasks work. This is because IDB transactions auto commits when there are no more pending callbacks to it.

**Comment by aboodman** [comment]
I think if we do the dd1 solution to instant this will automatically fix itself! But we should document itmt.

**Comment by aboodman** [comment]
No longer relevant!
