### ISSUE TITLE
Figure out right target chunk size for btree

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#630]
Right now it is at **8KiB**:

```
writeSubRead 16MB total, 128 subs total, 5 subs dirty, 16kb read per sub 50/75/90/95%=559.40,585.30,658.20,658.20ms/op (5 runs sampled)
```

A quick test with **16KiB**:

```
writeSubRead 16MB total, 128 subs total, 5 subs dirty, 16kb read per sub 50/75/90/95%=939.10,994.50,1346.10,1346.10ms/op (5 runs sampled)
```

And **4KiB**:

```
writeSubRead 16MB total, 128 subs total, 5 subs dirty, 16kb read per sub 50/75/90/95%=167.30,170.90,177.10,177.10ms/op (5 runs sampled)
```

And **2KiB**:

```
writeSubRead 16MB total, 128 subs total, 5 subs dirty, 16kb read per sub 50/75/90/95%=196.40,211.40,223.40,223.40ms/op (5 runs sampled)
```

We need to make sure we are optimizing for the right platform as well.

**Comment by aboodman** [comment]
@arv @grgbkr are we happy with our current chunk size?

**Comment by arv** [comment]
I think we should run some experiments. The current chunk size was based on early experiments but those were not using the BTree

**Comment by arv** [comment]
Also, are the perf benchmarks realistic? If they are, we should change it to **4KiB**

**Comment by aboodman** [comment]
We did some extensive testing of the performance of IDB back in the day (they are in the gdrive). Somebody needs to load those back into memory and ensure we like the chunk size we have picked makes most sense across devices and use cases.

**Comment by aboodman** [comment]
I think we should prioritize this just because Erik's quick test above shows there might be performance lying on the ground.

Erik's idea:

- run the entire perf suite on a variety of browsers and devices so we're comparing our own actual benchmarks

**Comment by arv** [comment]
I posted a PR draft that visualizes the different results for 8, 16 & 32KB min target chunk size.

https://github.com/rocicorp/replicache/pull/870

**Comment by arv** [comment]
I moved this to codesandbox.

https://codesandbox.io/s/repl-btree-chunk-size-wnp5vy?file=/src/index.js
https://wnp5vy.csb.app/

**Comment by aboodman** [comment]
Interesting -- I can't make any clear takeaway from this :-).

**Comment by aboodman** [comment]
What I'm saying is that based on this I would not change anything at this
time. Does anyone disagree? @grgbkr @phritz

**Comment by phritz** [comment]
I do not disagree

**Comment by arv** [comment]
I do not disagree.

Closing.
