### ISSUE TITLE
For some reason Replicache performance is absurdly bad when Chrome dev tools is open

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#634]
All the perf tests decrease like 5x-10x (!!). I have no idea what is going on but this is a common thing for developers to experience since they basically work with devtools open. We need to figure this out.

**Comment by aboodman** [comment]
Fixit to investigate. This was reported by calvin of Eleventh.

**Comment by aboodman** [comment]
Alright, I figured this out!

<img width="743" alt="Screen Shot 2021-11-19 at 10 27 04 AM" src="https://user-images.githubusercontent.com/80388/142687530-e5f04e03-14a9-452c-be57-35ffdaa73142.png">
-- https://developer.chrome.com/blog/wasm-debugging-2020/

In the following screencap, the top run is with devtools open, the second is with it closed:
<img width="958" alt="screen_shot_2021-11-19_at_10 21 38_am" src="https://user-images.githubusercontent.com/80388/142687444-85102682-426c-4c04-a3f6-5fb615d30191.png">

So our hashing is over 10x slower with devtools open because of this "tiering down" behavior in Chrome.

**Comment by aboodman** [comment]
OK what we've decided to do here is switch back to the native hash function (see #605 ) so closing this.

**Comment by aboodman** [comment]
Guess it make sense to leave open until fixed.

**Comment by grgbkr** [comment]
Fixed by a3887061c3dacf4f9803dc3c8d98d815b22bad88
