### ISSUE TITLE
TextEncoder not Defined

### ISSUE THREAD

**Issue by AndrewDragonCh** [rocicorp/replicache#639]
I'm running the little example code in the documentation, and whenever I run it, it throws an error that says:
```
error - node_modules/replicache/out/replicache.mjs (2598:0) @ eval
ReferenceError: TextEncoder is not defined
```
Any idea why this is? Thanks,

**Comment by aboodman** [comment]
Is this error in the browser or from the server?

**Comment by AndrewDragonCh** [comment]
It's taken directly from the server console. The browser has a bunch of errors as well, but I only posted the console one. Do you want the errors from the browser?

**Comment by arv** [comment]
TextEncoder is part of the browser API. Is this code running in a node environment by any chance? Also, if this is in NodeJS you need version 11 or later: https://nodejs.org/api/util.html#class-utiltextencoder

**Comment by aboodman** [comment]
@Dragonaere -- going to assume this addressed your question, if not please reopen and provide more details. thanks!
