### ISSUE TITLE
Cannot change `pusher` or `puller` after initialization

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#685]
I think this is a regression in 8.0, but I'm not sure:

```ts
const r = new Replicache();
r.pusher = ...
r.puller = ...
```

The pusher and puller impls won't get called because we create a `NullConnectionLoop` at startup and it is never changed. I think it might work OK if you put a no-op pusher/puller in there instead though.

**Comment by aboodman** [comment]
@grgbkr think this was fallout of some refactoring you did. Sorry there was no sufficient coverage to catch this.

**Comment by grgbkr** [comment]
Did not realize this was part of the API.

@aboodman What is the use case for changing pusher or puller after initialization?  I'm sure I can fix this, but am wondering if its better to just remove this part of the API, and make these be provided at time of constructing Replicache.

**Comment by aboodman** [comment]
I think we had a use case for changing some other configuration (maybe some of the rate limiting controls) and decided we may as well make the entire config interface mutable. I can't remember anything specific to pusher/puller -- maybe @arv does. I think we just thought the API was more consistent thing way.

I think it's clear that given `pusher` and `puller` are functions, you can clearly make them stubs and swap what they point to, so this isn't *necessary*.

I guess I don't have a strong opinion here. I do like removing things we don't have a clear need for as it constrains future development.

**Comment by arv** [comment]
I went through all the options at one point thinking which ones must be readonly to keep semantics sane. Everything else was made read-write to allow flexibility.

https://github.com/rocicorp/replicache/pull/443

**Comment by grgbkr** [comment]
Let me see if i can support it without overly complicating the code.

**Comment by grgbkr** [comment]
This was easy enough to fix without changing the API.
