### ISSUE TITLE
When pull fails it doesn't provide details

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#690]
I hit this, as did a user. We set the `cause` of the exception, here:

https://github.com/rocicorp/replicache/blob/16d2597163a88c65f51d6632bf1b03fd294769cf/src/puller.ts#L101

But this doesn't show up in the console anywhere so it's hard to know what's going wrong. Maybe we should include the causes's message in our message?

Or maybe we don't even need this `PullError` abstraction anymore.

**Comment by arv** [comment]
They just need to use a better browser =P

![image](https://user-images.githubusercontent.com/45845/142043879-0e0aff02-9bf2-4fc5-b83e-9d8d3ddcafcc.png)

Maybe related [chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1211260&q=error%20cause%20component%3APlatform%3EDevTools&can=2)?

**Comment by aboodman** [comment]
Wow! What browser is that.

But in any case, we can't build features that don't work right for the majority browser ;-).

**Comment by arv** [comment]
I'm just thinking that Chrome will fix this in the near term so it might not be worth spending time on.

Also, the latest Node.js also prints cause for stack traces.

**Comment by aboodman** [comment]
If it's going to get fixed by Chromium and pushed out to stable like tomorrow or this week sure. But otherwise, let's fix.
