### ISSUE TITLE
Investigate scan performance

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#711]
A user found that a scan of a large amount of data (1300 items, roughly 2MB) took 57ms, or roughly `2048/57*1000 = ~36MB/s` whereas our benchmarks say we should expect `1024/5*1000 ~= 200MB/s`. Profile and screenshot attached:

<img width="1688" alt="Screen Shot 2021-11-17 at 5 27 43 PM" src="https://user-images.githubusercontent.com/80388/142546066-fff39196-a507-4860-9c8d-f771e0801265.png">

[inmemory-profile (1).json.zip](https://github.com/rocicorp/replicache/files/7567187/inmemory-profile.1.json.zip)

As a fixit, we should investigate:

* Can we reproduce this worse performance with bigger scans?
* This was in the context of write/sub/read (the read does this big scan) does doing a big scan in that context reproduce this worse performance?
* The profile says it is spending a lot of time GC'ing under asserts. If we disable the asserts does it reduce GC frequency? (I don't see any reason why this assert should allocate, but as a quick test)
* Any other low hanging fruit to increase scan performance?

This is a fixit project so timebox to one day. Hopefully yields benefits, but if not, hopefully threads to pull on for later.

**Comment by arv** [comment]
I'm looking at this and I see that it is using 570MB of memory and the minor GC takes 38ms. It collects about 4MB at this time.

<img width="533" alt="Screen Shot 2021-11-19 at 11 20 09" src="https://user-images.githubusercontent.com/45845/142679405-a28a683e-1d86-46bc-af9e-1c44f42eaf1b.png">
 
 I'm trying to setup an environment where we are using this much memory and see if that impacts the perf tests.
