### ISSUE TITLE
add scan perf to envelope

### ISSUE THREAD

**Issue by phritz** [rocicorp/replicache#747]
- should be close to fastest possible scan of js map speed (1MB/ms would be rough memory speed)
- add perf benchmark

**Comment by aboodman** [comment]
We have already added it to the benchmarks. I think we just need to talk about this and decide what the right target is for the envelope.

**Comment by aboodman** [comment]
We are currently at 3ms/MB according to our benchmarks, but that's scanning 1MB. I wonder if it would be better if we scanned more. We should add a 10MB to the benchmark.

I'm fine with releasing GA if we're at 3ms/MB rather than 1ms.

**Comment by arv** [comment]
I added one more test to the perf tests. I think we also need to update rocicorp/mono#134 ?

**Comment by aboodman** [comment]
I updated rocicorp/mono#134 just now with the goal (1MB/s) but when this becomes
documentation we will document our current status.
