### ISSUE TITLE
We decided to require `name` correct?

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#795]
Right now if you don't provide one the created database name is `undefined`:

<img width="510" alt="Screen Shot 2022-01-25 at 5 28 44 PM" src="https://user-images.githubusercontent.com/80388/151099246-32803395-9533-43cd-a204-94e5a3735d8d.png">

**Comment by aboodman** [comment]
I see - we made it required in the typescript type (abf8eccba602014745c95e0b47775b3310eb335a) but there's no runtime checking. I wonder what our policy for this kind of thing should be?

**Comment by arv** [comment]
This one should probably be a runtime check too.
