### ISSUE TITLE
Could we prefix the idb database names with "rep:"?

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#836]
<img width="732" alt="Screen Shot 2022-02-10 at 10 12 35 PM" src="https://user-images.githubusercontent.com/80388/153557482-70309402-4774-405e-a8e5-67f616803168.png">

It would be useful for common development hosts such as localhost:3000 to be able to see which DBs are ours vs other systems'.

Perhaps we should do this prior to v9 stable.

**Comment by arv** [comment]
Seems fine.
