### ISSUE TITLE
Is replicache open source or source available?

### ISSUE THREAD

**Issue by gotjoshua** [rocicorp/replicache#837]
Does the team consider this software to be open source? I understand that commercial users are expected to pay if there are more than 500 monthly active clients. Is that on the honors system?

**Comment by aboodman** [comment]
Replicache is currently BSL licensed: https://github.com/rocicorp/replicache/blob/main/LICENSE, so no it's not Open Source.

We have not yet implemented licensing or billing. Payment is currently just on honor system.

For our General Availability release of Replicache -- expected sometime early this year -- we plan to update our license and implement billing. Here is how we are currently thinking it will work:

* The product will become more classically Source Available. The fact that the code is publicly viewable now makes it easy to confuse with Open Source and frequently brings up IP concerns. We will instead make the repo closed by default, but paying customers will get access to the source (for e.g., debugging)
* We will change the license away from BSL to a custom Source Available - style license.
* The Replicache constructor will begin requiring a license key, which you can get by running a script in the npm package.
* Replicache will be free (as in beer) for any non-commercial use
* Replicache will have a 2-month free tier-kicking period for commercial uses
* To use Replicache beyond the 2-month trial period for commercial purposes will require a paid license

HTH
