### ISSUE TITLE
Share a unique per-profile ID with server in push and pull

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#838]
It is useful for some applications to have a per-browser-profile unique ID associated with Replicache. For example, to manage the extent of the sync window, you want to do that on a per-profile basis, not a per-client.

Users can already generate such a unique ID and store it themselves, but since Replicache is also already going to do that for licensing we may as well send along our ID in the request.

**Comment by aboodman** [comment]
@phritz can we do this as part of licensing work.

**Comment by phritz** [comment]
Yes
