### ISSUE TITLE
It would be nice to stamp the version of Replicache into the class as a read-only field

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#845]
... for debugging purposes.

**Comment by aboodman** [comment]
See https://github.com/rocicorp/reflect/commit/e32368a7544dcfaeb84c9310d8a0c21493359b7c for an example of how to do this.

**Comment by arv** [comment]
For Replicache we should use esbuild to reduce code size.

**Comment by arv** [comment]
Fixed in cbb2e6ef85dfdfc53686f1783b5d17da0753793d
