### ISSUE TITLE
Do we really swallow subscriptions that throw by default??

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#862]
I just did `useSubscribe(...thing that throws...)` and ... nothing showed up anywhere. What the? It looks like we swallow errors from subscription functions.

We should send them to `console.error()` by default.

**Comment by aboodman** [comment]
This is pretty surprising and bad so we should fix for GA.

**Comment by arv** [comment]
Yup, we do nothing if `onError` is not provided. We should at least call `console.error`.

https://github.com/rocicorp/replicache/blob/main/src/replicache.ts#L1140
