### ISSUE TITLE
RFE: Allow subscribe to take arguments separately, share duplicate invocations

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#863]
If I understand correctly, currently `subscribe()` take a single function argument. If two callers call subscribe with an identical function object, two subscriptions will be created. More commonly, if two callers call subscribe with different closures over the same function object, two subscriptions will be created and there is no way for them to be deduped (because `subscribe` doesn't have any way to know about the enclosed function and its arguments).

This incentivizes users of Replicache to do the "container" dance of trying to figure out where in the component tree to put calls to subscribe to share their results.

It would be cool if subscribe could take a list of arguments too. Then it could dedupe on the function and its arguments. Then the style of using Replicache could simply be to subscribe for exactly what you want in every component. If a subscription already exists that is the same (as deduped by function + args) then the subscription will be reused.

Sorry if I'm missing something about the current state. Been awhile since I've thought about this.

**Comment by arv** [comment]
What is the container dance?

We would also need to dedupe the options (`onData`, `onError` and `onDone`)

**Comment by aboodman** [comment]
By "container dance" I mean trying to figure out which components in a React app should be "containers" (have the state and do the loading).

> We would also need to dedupe the options (onData, onError and onDone)

No, I'm thinking that we'd still have multiple listeners for each subscription so those would be separate. We're just avoiding re-running the subscription if two people want the same data.

Anyways I specifically think we shouldn't do this right now until we have more information so closing it.
