### ISSUE TITLE
decide what to do for the license status check (potential) foot-gun

### ISSUE THREAD

**Issue by phritz** [rocicorp/replicache#909]
Moving to an issue so it doesn't get dropped: https://rocicorp.slack.com/archives/G013XFG80JC/p1648231510725349

Currently the kill switch is triggered if the license is anything other thank Valid (so, unknown or Invalid). I think the most prudent thing is to separate the license status from the activate kill switch bit, and just never set the bit for now. We can discuss doing so at the first point where we actually want it.

**Comment by aboodman** [comment]
I agree with you. Thanks for patiently waiting me to see the light here.
