### ISSUE TITLE
Add `allowNull` option to `CreateIndexOptions`

### ISSUE THREAD

**Issue by tslocke** [rocicorp/replicache#913]
It's common in relational modelling to have optional fkeys. I'd like to be able to index fkeys without null values being an issue. They should just not be present in the index.

Actually it seems this is what Replicache does now, it just splurges a ton of warning to the console: e.g. "Not indexing value {...} Error: No value at path: /parentID"

Can these just be silently ignored? Or at least provide an option to `createIndex` to silence the warnings?

Thanks

**Comment by aboodman** [comment]
We felt a bit weird ignoring them completely that's why we went with the warning. Would you be OK if it was a verbose level log instead?

**Comment by tslocke** [comment]
Yeah I guess, although it kinda seems like avoiding the issue. If you added an `allowNull` option you could go the other way and make it an actual error.

**Comment by aboodman** [comment]
Hadn't considered the option to make it an error. Good idea!

**Comment by aboodman** [comment]
So the concrete proposal is:

1.  Add `nullBehavior` property to `CreateIndexOptions` with possible values `"error"`, `"skip"`, and default of `"error"`.
2. When `nullBehavior` is `"error"` indexing that encounters a null prints an error to console (instead of warning) and skip the row (but continue indexing).
3. When `nullBehavior` is '"skip"` indexing that encounters a null just silently skips it.

Note that the `nullBehavior` flag is a property of the index definition and lasts beyond the call to `createIndex`.

**Comment by tslocke** [comment]
For 2. would it make sense to raise an exception? In development it’s always better to fail as early as possible but maybe this is counterproductive in production.

**Comment by aboodman** [comment]
I actually think maybe we should skip the flag and just make it behave the way you asked. I'm not sure complaining about this is all that useful. Thinking about it from user pov just not indexing values with missing or null fields seems like what I'd expect it to do.

**Comment by arv** [comment]
I agree. There needs to be an enum value for `"abort"`/`"throw"`

**Comment by arv** [comment]
I think this needs more design:

At the moment the error is thrown when `evaluateJSONPointer` returns `undefined`.

`evaluateJSONPointer` returns `undefined` under these circumstances.
- The JSON path is not valid (for example `'abc'`)
- Trying to use a non numeric index when indexing into an array (ie `/arrayValue/x`)
- target is `null`
- Property is missing (ie path `/a` in `{b: 42}`)

With this PR all of the above is covered by the `nullBehavior`.

Maybe the right API is more along the lines of:

```
errorBehavior: LogLevel | 'throw'
```

**Comment by ingar** [comment]
I see.  Of the 4 cases above where `undefined` is returned, the last 3 can be considered different cases of "nonexistent value at pointer", whereas the first one is a validation error.

Would it make sense to:
1. validate the `jsonPointer` at index creation time, and throw an error if the syntax is incorrect
2. add an option `emptyValueBehavior` with the same union suggested — logging or `throw`

This way, the behavior we are specifying is only the case where the valid jsonPointer is pointing to some value that doesn't exist.

**Comment by tslocke** [comment]
> add an option emptyValueBehavior with the same union suggested — logging or throw

Surely log, throw or skip? The skip option was the point of this ticket in the first place.

**Comment by tslocke** [comment]
Is there much chance this change could make it into a quick patch release? The current behaviour absolutely swamps the dev console with useless messages in my app. I have taken to hacking Replicache in `node_modules` to silence it, but in production the noise is still there.

**Comment by aboodman** [comment]
Sorry @tslocke. API stuff, we're slow on this sometimes because we don't want to do something wrong then have to maintain it forever (also when you originally reported the bug we were heads down in release mode). Yes, we can get a patch release out with something for this very soon.
