### ISSUE TITLE
User request: Golang backend sample

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#922]
See original request here: https://github.com/rocicorp/replicache-todo/issues/2.

**Comment by gunta** [comment]
+1

**Comment by aboodman** [comment]
I don't think we can do this in the near term, we are a small team and most of our customers use JS on the backend. The more samples we have, the more we have to maintain. Sorry. Hopefully we can make the JS backends and related docs clear enough that people feel confident doing this if they want.
